'use strict';

// Named capabilities remain live; this factory installs no listeners.
function createClipboard(dependencies) {


    function showEditorToast(msg) {
        if (!dependencies.externalChangeToast) {
            dependencies.externalChangeToast = document.createElement('div');
            dependencies.externalChangeToast.className = 'external-change-toast';
            dependencies.externalChangeToast.setAttribute('role', 'status');
            const messageDiv = document.createElement('div');
            messageDiv.className = 'toast-message';
            dependencies.externalChangeToast.appendChild(messageDiv);
            document.body.appendChild(dependencies.externalChangeToast);
        }
        const messageDiv = dependencies.externalChangeToast.querySelector('.toast-message');
        messageDiv.textContent = msg || 'File modified externally. Click outside editor to reload.';
        // Show
        if (dependencies.toastHideTimer) clearTimeout(dependencies.toastHideTimer);
        requestAnimationFrame(() => {
            dependencies.externalChangeToast.classList.add('show');
        });
        // Auto-hide after 5 seconds
        dependencies.toastHideTimer = setTimeout(() => {
            dependencies.externalChangeToast.classList.remove('show');
        }, 5000);
    }


    function createDragCursor() {
        if (!dependencies.dragCursor) {
            dependencies.dragCursor = document.createElement('div');
            dependencies.dragCursor.className = 'drag-cursor';
            dependencies.dragCursor.style.cssText = 'position:fixed;width:2px;height:20px;background:#0969da;pointer-events:none;z-index:9999;display:none;';
            document.body.appendChild(dependencies.dragCursor);
        }
    }


    function showDragCursor(x, y) {
        createDragCursor();
        // Try to get caret position
        const range = document.caretRangeFromPoint(x, y);
        if (range) {
            const rect = range.getBoundingClientRect();
            // If rect has valid dimensions, use it
            if (rect.height > 0) {
                dependencies.dragCursor.style.left = rect.left + 'px';
                dependencies.dragCursor.style.top = rect.top + 'px';
                dependencies.dragCursor.style.height = rect.height + 'px';
                dependencies.dragCursor.style.display = 'block';
            } else {
                // For empty lines, find the nearest element and position there
                const element = document.elementFromPoint(x, y);
                if (element && dependencies.editor.contains(element)) {
                    const elemRect = element.getBoundingClientRect();
                    dependencies.dragCursor.style.left = (elemRect.left + 5) + 'px';
                    dependencies.dragCursor.style.top = elemRect.top + 'px';
                    dependencies.dragCursor.style.height = Math.max(elemRect.height, 20) + 'px';
                    dependencies.dragCursor.style.display = 'block';
                }
            }
        } else {
            // Fallback: show cursor at mouse position
            dependencies.dragCursor.style.left = x + 'px';
            dependencies.dragCursor.style.top = y + 'px';
            dependencies.dragCursor.style.height = '20px';
            dependencies.dragCursor.style.display = 'block';
        }
    }


    function hideDragCursor() {
        if (dependencies.dragCursor) {
            dependencies.dragCursor.style.display = 'none';
        }
    }


    function readAndInsertImage(file) {
        const reader = new FileReader();
        reader.onload = function(event) {
            dependencies.logger.log('FileReader onload called');
            const dataUrl = event.target.result;

            // Send to extension to save as file (filename always generated by extension as timestamp)
            dependencies.host.saveImageAndInsert(dataUrl);
            dependencies.logger.log('Image sent to extension for saving');
        };
        reader.onerror = function(err) {
            dependencies.logger.error('FileReader error:', err);
        };
        reader.readAsDataURL(file);
    }

    return { showEditorToast, createDragCursor, showDragCursor, hideDragCursor, readAndInsertImage };
}

module.exports = { createClipboard };
