'use strict';
// Construction defines capabilities; bootstrap controls the original initialization order.
function createClipboard(dependencies) {
    let externalChangeToast, toastHideTimer, dragCursor;
    function showEditorToast(msg) {
        if (!externalChangeToast) {
            externalChangeToast = document.createElement('div');
            externalChangeToast.className = 'external-change-toast';
            externalChangeToast.setAttribute('role', 'status');
            const messageDiv = document.createElement('div');
            messageDiv.className = 'toast-message';
            externalChangeToast.appendChild(messageDiv);
            document.body.appendChild(externalChangeToast);
        }
        const messageDiv = externalChangeToast.querySelector('.toast-message');
        messageDiv.textContent = msg || 'File modified externally. Click outside editor to reload.';
        // Show
        if (toastHideTimer)
            clearTimeout(toastHideTimer);
        requestAnimationFrame(() => {
            externalChangeToast.classList.add('show');
        });
        // Auto-hide after 5 seconds
        toastHideTimer = setTimeout(() => {
            externalChangeToast.classList.remove('show');
        }, 5000);
    }
    function createDragCursor() {
        if (!dragCursor) {
            dragCursor = document.createElement('div');
            dragCursor.className = 'drag-cursor';
            dragCursor.style.cssText = 'position:fixed;width:2px;height:20px;background:#0969da;pointer-events:none;z-index:9999;display:none;';
            document.body.appendChild(dragCursor);
        }
    }
    function showDragCursor(x, y) {
        createDragCursor();
        // Try to get caret position
        const range = document.caretRangeFromPoint(x, y);
        if (range) {
            const rect = range.getBoundingClientRect();
            // If rect has valid dimensions, use it
            if (rect.height > 0) {
                dragCursor.style.left = rect.left + 'px';
                dragCursor.style.top = rect.top + 'px';
                dragCursor.style.height = rect.height + 'px';
                dragCursor.style.display = 'block';
            }
            else {
                // For empty lines, find the nearest element and position there
                const element = document.elementFromPoint(x, y);
                if (element && dependencies.editor.contains(element)) {
                    const elemRect = element.getBoundingClientRect();
                    dragCursor.style.left = (elemRect.left + 5) + 'px';
                    dragCursor.style.top = elemRect.top + 'px';
                    dragCursor.style.height = Math.max(elemRect.height, 20) + 'px';
                    dragCursor.style.display = 'block';
                }
            }
        }
        else {
            // Fallback: show cursor at mouse position
            dragCursor.style.left = x + 'px';
            dragCursor.style.top = y + 'px';
            dragCursor.style.height = '20px';
            dragCursor.style.display = 'block';
        }
    }
    function hideDragCursor() {
        if (dragCursor) {
            dragCursor.style.display = 'none';
        }
    }
    function readAndInsertImage(file) {
        const reader = new FileReader();
        reader.onload = function (event) {
            dependencies.logger.log('FileReader onload called');
            const dataUrl = event.target.result;
            // Send to extension to save as file (filename always generated by extension as timestamp)
            dependencies.host.saveImageAndInsert(dataUrl);
            dependencies.logger.log('Image sent to extension for saving');
        };
        reader.onerror = function (err) {
            dependencies.logger.error('FileReader error:', err);
        };
        reader.readAsDataURL(file);
    }
    let initializeExternalChangeToastDone = false;
    function initializeExternalChangeToast() {
        if (initializeExternalChangeToastDone)
            return;
        initializeExternalChangeToastDone = true;
        (externalChangeToast = null);
        (toastHideTimer = null);
        (dragCursor = null);
        document.addEventListener('dragenter', function (e) {
            if (dependencies.editor.contains(e.target) || e.target === dependencies.editor) {
                e.preventDefault();
                e.stopPropagation();
                dependencies.logger.log('dragenter on editor');
                dependencies.editor.classList.add('drag-over');
            }
        });
        document.addEventListener('dragover', function (e) {
            if (dependencies.editor.contains(e.target) || e.target === dependencies.editor) {
                e.preventDefault();
                e.stopPropagation();
                if (e.dataTransfer) {
                    e.dataTransfer.dropEffect = 'copy';
                }
                dependencies.editor.classList.add('drag-over');
                // Show cursor at drop position
                showDragCursor(e.clientX, e.clientY);
            }
        });
        document.addEventListener('dragleave', function (e) {
            if (e.target === dependencies.editor) {
                dependencies.editor.classList.remove('drag-over');
                hideDragCursor();
            }
        });
        document.addEventListener('drop', function (e) {
            if (!dependencies.editor.contains(e.target) && e.target !== dependencies.editor) {
                return; // Not on editor
            }
            e.preventDefault();
            e.stopPropagation();
            dependencies.editor.classList.remove('drag-over');
            hideDragCursor();
            dependencies.logger.log('Drop event fired on editor');
            dependencies.logger.log('dataTransfer:', e.dataTransfer);
            dependencies.logger.log('files:', e.dataTransfer?.files);
            dependencies.logger.log('items:', e.dataTransfer?.items);
            dependencies.logger.log('types:', e.dataTransfer?.types);
            // Get drop position first
            const dropRange = document.caretRangeFromPoint(e.clientX, e.clientY);
            if (dropRange) {
                const sel = window.getSelection();
                sel.removeAllRanges();
                sel.addRange(dropRange);
            }
            // Try to get files first
            const files = e.dataTransfer?.files;
            if (files && files.length > 0) {
                const file = files[0];
                dependencies.logger.log('Dropped file from files:', file.name, file.type, file.size);
                if (file.type.startsWith('image/')) {
                    readAndInsertImage(file);
                    return;
                }
            }
            // Fallback: try items
            const items = e.dataTransfer?.items;
            if (items && items.length > 0) {
                for (let i = 0; i < items.length; i++) {
                    const item = items[i];
                    dependencies.logger.log('Item:', item.kind, item.type);
                    if (item.kind === 'file' && item.type.startsWith('image/')) {
                        const file = item.getAsFile();
                        if (file) {
                            dependencies.logger.log('Got file from items:', file.name, file.size);
                            readAndInsertImage(file);
                            return;
                        }
                    }
                }
            }
            // Check for file URI drop (from Finder/Explorer via VS Code)
            const uriList = e.dataTransfer?.getData('text/uri-list');
            const plainText = e.dataTransfer?.getData('text/plain');
            dependencies.logger.log('URI list:', uriList);
            dependencies.logger.log('Plain text:', plainText);
            // Try to get file path from various sources
            let filePath = null;
            if (uriList) {
                // Parse URI list (can contain multiple URIs, one per line)
                const uris = uriList.split('\n').filter(u => u.trim());
                for (const uri of uris) {
                    if (uri.startsWith('file://')) {
                        // Check if it's an image
                        if (uri.match(/\.(png|jpg|jpeg|gif|webp|svg)$/i)) {
                            filePath = decodeURIComponent(uri.replace('file://', ''));
                            break;
                        }
                    }
                }
            }
            if (!filePath && plainText) {
                // Sometimes the path is in plain text
                if (plainText.startsWith('file://')) {
                    if (plainText.match(/\.(png|jpg|jpeg|gif|webp|svg)$/i)) {
                        filePath = decodeURIComponent(plainText.replace('file://', ''));
                    }
                }
                else if (plainText.startsWith('/') && plainText.match(/\.(png|jpg|jpeg|gif|webp|svg)$/i)) {
                    // Direct file path
                    filePath = plainText;
                }
            }
            if (filePath) {
                dependencies.logger.log('Found image file path:', filePath);
                // Send to extension to read the file
                dependencies.host.readAndInsertImage(filePath);
                return;
            }
            // Check for web URL drop
            const url = uriList || plainText;
            if (url && url.startsWith('http') && url.match(/\.(png|jpg|jpeg|gif|webp|svg)(\?.*)?$/i)) {
                dependencies.logger.log('Dropped web image URL:', url);
                // Insert as markdown image with URL
                const img = document.createElement('img');
                img.src = url;
                img.alt = 'image';
                img.style.maxWidth = '100%';
                const sel = window.getSelection();
                if (sel && sel.rangeCount) {
                    const range = sel.getRangeAt(0);
                    range.insertNode(img);
                    range.setStartAfter(img);
                    range.collapse(true);
                }
                else {
                    dependencies.editor.appendChild(img);
                }
                dependencies.syncMarkdown();
                return;
            }
            dependencies.logger.log('No image found in drop');
        });
        dependencies.editor.addEventListener('copy', function (e) {
            if (e.target.closest && e.target.closest('.front-matter'))
                return;
            if (dependencies.isSourceMode)
                return;
            const sel = window.getSelection();
            if (!sel || sel.rangeCount === 0 || sel.isCollapsed)
                return;
            e.preventDefault();
            // Get the selected HTML
            const range = sel.getRangeAt(0);
            const fragment = range.cloneContents();
            const tempDiv = document.createElement('div');
            tempDiv.appendChild(fragment);
            // Handle triple-click selection: when selection ends at offset 0 of next element,
            // remove the trailing empty element that was included
            const endOffset = range.endOffset;
            if (endOffset === 0 && tempDiv.lastChild) {
                const lastChild = tempDiv.lastChild;
                // Check if the last child is empty or only contains empty elements
                const lastChildText = lastChild.textContent || '';
                if (lastChildText.trim() === '') {
                    tempDiv.removeChild(lastChild);
                }
            }
            // Handle triple-click on nested list item: when selection includes parent li with only nested list,
            // unwrap to get just the nested list content
            // Pattern: <li><ul><li>content</li></ul></li> -> should become just the nested li content
            if (tempDiv.childNodes.length === 1) {
                const onlyChild = tempDiv.childNodes[0];
                if (onlyChild.nodeType === 1 && onlyChild.tagName.toLowerCase() === 'li') {
                    // Check if this li has no direct text content, only a nested list
                    let hasDirectText = false;
                    let nestedList = null;
                    for (const child of onlyChild.childNodes) {
                        if (child.nodeType === 3 && child.textContent.trim()) {
                            hasDirectText = true;
                            break;
                        }
                        if (child.nodeType === 1) {
                            const tag = child.tagName.toLowerCase();
                            if (tag === 'ul' || tag === 'ol') {
                                nestedList = child;
                            }
                            else if (tag !== 'br') {
                                // Has other inline content
                                hasDirectText = true;
                                break;
                            }
                        }
                    }
                    if (!hasDirectText && nestedList) {
                        // Replace the parent li with the nested list's content
                        tempDiv.innerHTML = '';
                        for (const li of nestedList.children) {
                            tempDiv.appendChild(li.cloneNode(true));
                        }
                    }
                }
            }
            const selectedHtml = dependencies.clipboardHtml(tempDiv);
            dependencies.logger.log('Copy - selected HTML:', selectedHtml.substring(0, 500));
            dependencies.logger.log('Copy - tempDiv children count:', tempDiv.childNodes.length);
            dependencies.logger.log('Copy - tempDiv children:', Array.from(tempDiv.childNodes).map(n => n.nodeName + '(' + (n.textContent || '').substring(0, 30) + ')').join(', '));
            try {
                let md = '';
                // Check if the selection is just text (no block elements)
                const hasBlockElements = tempDiv.querySelector('p, h1, h2, h3, h4, h5, h6, ul, ol, li, pre, blockquote, table, hr');
                dependencies.logger.log('Copy - hasBlockElements:', hasBlockElements ? hasBlockElements.tagName : 'null');
                if (!hasBlockElements) {
                    // Selection is just text - need to check if it's a full element selection or partial
                    const startContainer = range.startContainer;
                    let contextNode = startContainer;
                    // Find the nearest block-level parent
                    while (contextNode && contextNode !== dependencies.editor) {
                        if (contextNode.nodeType === 1) {
                            const tag = contextNode.tagName.toLowerCase();
                            if (['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'li', 'pre', 'blockquote', 'td', 'th'].includes(tag)) {
                                break;
                            }
                        }
                        contextNode = contextNode.parentNode;
                    }
                    dependencies.logger.log('Copy - context node:', contextNode ? contextNode.tagName : 'none');
                    // Check if the selection covers the entire text content of the context node
                    const selectedText = sel.toString();
                    let isFullSelection = false;
                    if (contextNode && contextNode !== dependencies.editor && contextNode.nodeType === 1) {
                        const tag = contextNode.tagName.toLowerCase();
                        // Get the text content of the context node (excluding nested lists for li)
                        let contextText = '';
                        if (tag === 'li') {
                            // For list items, get text content excluding nested ul/ol
                            for (const child of contextNode.childNodes) {
                                if (child.nodeType === 3) {
                                    contextText += child.textContent;
                                }
                                else if (child.nodeType === 1) {
                                    const childTag = child.tagName.toLowerCase();
                                    if (childTag !== 'ul' && childTag !== 'ol' && childTag !== 'input') {
                                        contextText += child.textContent;
                                    }
                                }
                            }
                        }
                        else {
                            contextText = contextNode.textContent;
                        }
                        contextText = contextText.trim();
                        // Check if selection matches the full text content
                        isFullSelection = selectedText.trim() === contextText;
                        dependencies.logger.log('Copy - selectedText:', selectedText, 'contextText:', contextText, 'isFullSelection:', isFullSelection);
                        if (isFullSelection) {
                            // Full selection - apply context-specific formatting
                            if (tag === 'li') {
                                // Check if it's inside a list and get the proper indent
                                let indent = '';
                                let listParent = contextNode.parentNode;
                                while (listParent && listParent !== dependencies.editor) {
                                    if (listParent.tagName && (listParent.tagName.toLowerCase() === 'ul' || listParent.tagName.toLowerCase() === 'ol')) {
                                        // Check if this list is nested inside another li
                                        if (listParent.parentNode && listParent.parentNode.tagName && listParent.parentNode.tagName.toLowerCase() === 'li') {
                                            indent = '  ' + indent;
                                        }
                                    }
                                    listParent = listParent.parentNode;
                                }
                                // Check for checkbox
                                const checkbox = contextNode.querySelector(':scope > input[type="checkbox"]');
                                if (checkbox) {
                                    const checked = checkbox.checked ? 'x' : ' ';
                                    md = indent + '- [' + checked + '] ' + selectedText;
                                }
                                else {
                                    // Determine marker (- for ul, number for ol)
                                    const parentList = contextNode.parentNode;
                                    if (parentList && parentList.tagName && parentList.tagName.toLowerCase() === 'ol') {
                                        // Find the index of this li in the ol
                                        const siblings = Array.from(parentList.children).filter(c => c.tagName && c.tagName.toLowerCase() === 'li');
                                        const index = siblings.indexOf(contextNode) + 1;
                                        md = indent + index + '. ' + selectedText;
                                    }
                                    else {
                                        md = indent + '- ' + selectedText;
                                    }
                                }
                            }
                            else if (tag === 'h1') {
                                md = '# ' + selectedText;
                            }
                            else if (tag === 'h2') {
                                md = '## ' + selectedText;
                            }
                            else if (tag === 'h3') {
                                md = '### ' + selectedText;
                            }
                            else if (tag === 'h4') {
                                md = '#### ' + selectedText;
                            }
                            else if (tag === 'h5') {
                                md = '##### ' + selectedText;
                            }
                            else if (tag === 'h6') {
                                md = '###### ' + selectedText;
                            }
                            else if (tag === 'blockquote') {
                                // Add > prefix to each line
                                const lines = selectedText.split('\n');
                                md = lines.map(line => '> ' + line).join('\n');
                            }
                            else if (tag === 'pre') {
                                // Code block: copy as plain text without fences
                                md = selectedText;
                            }
                            else {
                                // Default: just the text
                                md = selectedText;
                            }
                        }
                        else {
                            // Partial selection - just use plain text
                            md = selectedText;
                        }
                    }
                    else {
                        // No context found, just use the text
                        md = sel.toString();
                    }
                }
                else {
                    // Selection contains block elements - process normally
                    dependencies.logger.log('Copy - processing block elements, childNodes count:', tempDiv.childNodes.length);
                    // Special case: If selection starts with text node followed by nested list,
                    // and the selection started inside a list item, we need to wrap the text as a list item
                    const firstChild = tempDiv.childNodes[0];
                    const hasNestedList = tempDiv.querySelector('ul, ol');
                    const startContainer = range.startContainer;
                    // Find if selection started inside a list item
                    let startLi = null;
                    let node = startContainer;
                    while (node && node !== dependencies.editor) {
                        if (node.nodeType === 1 && node.tagName && node.tagName.toLowerCase() === 'li') {
                            startLi = node;
                            break;
                        }
                        node = node.parentNode;
                    }
                    // Check if first child is text OR if it's a checkbox followed by text (task list case)
                    // Also check for inline elements (strong, em, a, code, etc.) that are not block elements
                    const isFirstChildText = firstChild && firstChild.nodeType === 3;
                    const isFirstChildInlineElement = firstChild && firstChild.nodeType === 1 &&
                        !['ul', 'ol', 'li', 'p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'pre', 'blockquote', 'table', 'hr', 'div'].includes(firstChild.tagName.toLowerCase());
                    const isTaskListSelection = firstChild && firstChild.nodeName === 'INPUT' &&
                        firstChild.type === 'checkbox' &&
                        tempDiv.childNodes.length >= 2 &&
                        tempDiv.childNodes[1].nodeType === 3;
                    dependencies.logger.log('Copy - firstChild is text:', isFirstChildText);
                    dependencies.logger.log('Copy - firstChild is inline element:', isFirstChildInlineElement);
                    dependencies.logger.log('Copy - isTaskListSelection:', isTaskListSelection);
                    dependencies.logger.log('Copy - hasNestedList:', !!hasNestedList);
                    dependencies.logger.log('Copy - startLi:', startLi ? 'found' : 'null');
                    dependencies.logger.log('Copy - startLi has checkbox:', startLi ? !!startLi.querySelector(':scope > input[type="checkbox"]') : false);
                    // If first child is text/inline element (or checkbox+text for task list), followed by a list, and we started in a list item
                    if ((isFirstChildText || isFirstChildInlineElement || isTaskListSelection) && hasNestedList && startLi) {
                        // Calculate indent based on list nesting level
                        let indent = '';
                        let listParent = startLi.parentNode;
                        while (listParent && listParent !== dependencies.editor) {
                            if (listParent.tagName && (listParent.tagName.toLowerCase() === 'ul' || listParent.tagName.toLowerCase() === 'ol')) {
                                if (listParent.parentNode && listParent.parentNode.tagName && listParent.parentNode.tagName.toLowerCase() === 'li') {
                                    indent = '  ' + indent;
                                }
                            }
                            listParent = listParent.parentNode;
                        }
                        // Determine marker type
                        const parentList = startLi.parentNode;
                        let marker = '-';
                        if (parentList && parentList.tagName && parentList.tagName.toLowerCase() === 'ol') {
                            const siblings = Array.from(parentList.children).filter(c => c.tagName && c.tagName.toLowerCase() === 'li');
                            const index = siblings.indexOf(startLi) + 1;
                            marker = index + '.';
                        }
                        // Get text content - for task list, it's the second child; for normal list, it's the first child
                        let textContent;
                        let startIndex; // Index to start processing remaining children
                        if (isTaskListSelection) {
                            // Task list: INPUT, #text, UL...
                            textContent = tempDiv.childNodes[1].textContent.trim();
                            startIndex = 2; // Skip INPUT and #text
                            // Get checkbox state from the copied INPUT element
                            const copiedCheckbox = firstChild;
                            const checked = copiedCheckbox.checked ? 'x' : ' ';
                            md = indent + '- [' + checked + '] ' + textContent + '\n';
                            dependencies.logger.log('Copy - task list: checkbox checked:', copiedCheckbox.checked, 'text:', textContent);
                        }
                        else {
                            // Normal list: #text or inline element, followed by UL...
                            // Collect all inline content before the nested list
                            let inlineContent = '';
                            startIndex = 0;
                            for (let i = 0; i < tempDiv.childNodes.length; i++) {
                                const child = tempDiv.childNodes[i];
                                if (child.nodeType === 1) {
                                    const tag = child.tagName.toLowerCase();
                                    if (tag === 'ul' || tag === 'ol') {
                                        // Found the nested list, stop collecting inline content
                                        startIndex = i;
                                        break;
                                    }
                                }
                                // Process inline content (text nodes and inline elements)
                                inlineContent += dependencies.mdProcessNode(child);
                            }
                            textContent = inlineContent.trim();
                            // Check for checkbox in the original list item
                            const checkbox = startLi.querySelector(':scope > input[type="checkbox"]');
                            if (checkbox) {
                                const checked = checkbox.checked ? 'x' : ' ';
                                md = indent + '- [' + checked + '] ' + textContent + '\n';
                            }
                            else {
                                md = indent + marker + ' ' + textContent + '\n';
                            }
                        }
                        // Process remaining children (the nested list)
                        for (let i = startIndex; i < tempDiv.childNodes.length; i++) {
                            const child = tempDiv.childNodes[i];
                            dependencies.logger.log('Copy - processing remaining child:', child.nodeName);
                            // Nested list should have increased indent
                            md += dependencies.mdProcessNode(child, indent + '  ');
                        }
                        dependencies.logger.log('Copy - used list item wrapping for text + nested list');
                    }
                    else {
                        md = dependencies.serializeMarkdownFragment(tempDiv);
                    }
                    md = md.trim();
                }
                dependencies.logger.log('Copy - converted markdown:', md.substring(0, 200));
                // Set clipboard data
                e.clipboardData.setData('text/plain', md);
                e.clipboardData.setData('text/html', selectedHtml);
                e.clipboardData.setData('text/x-binary-markdown', md);
            }
            catch (err) {
                dependencies.logger.error('Copy error:', err);
                // Fallback to plain text
                e.clipboardData.setData('text/plain', sel.toString());
            }
        });
        dependencies.editor.addEventListener('cut', function (e) {
            if (e.target.closest && e.target.closest('.front-matter'))
                return;
            if (dependencies.isSourceMode)
                return;
            const sel = window.getSelection();
            if (!sel || sel.rangeCount === 0 || sel.isCollapsed)
                return;
            e.preventDefault();
            dependencies.markAsEdited();
            // Get the selected HTML
            const range = sel.getRangeAt(0);
            const fragment = range.cloneContents();
            const tempDiv = document.createElement('div');
            tempDiv.appendChild(fragment);
            const selectedHtml = dependencies.clipboardHtml(tempDiv);
            // Convert to Markdown using the same logic as htmlToMarkdown()
            try {
                const md = dependencies.serializeMarkdownFragment(tempDiv);
                e.clipboardData.setData('text/plain', md);
                e.clipboardData.setData('text/html', selectedHtml);
                e.clipboardData.setData('text/x-binary-markdown', md);
            }
            catch (err) {
                e.clipboardData.setData('text/plain', sel.toString());
            }
            // Delete the selection
            range.deleteContents();
            dependencies.syncMarkdown();
        });
    }
    return {
        showEditorToast,
        createDragCursor,
        showDragCursor,
        hideDragCursor,
        readAndInsertImage,
        get externalChangeToast() { return externalChangeToast; }, set externalChangeToast(value) { externalChangeToast = value; },
        get toastHideTimer() { return toastHideTimer; }, set toastHideTimer(value) { toastHideTimer = value; },
        get dragCursor() { return dragCursor; }, set dragCursor(value) { dragCursor = value; },
        initializeExternalChangeToast
    };
}
module.exports = { createClipboard };
